In [2]:
import numpy as np

#### Vector-Vector Multiplication

In [3]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [4]:
u.shape

(4,)

In [5]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] #make sure vectors are same size
    
    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [6]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [7]:
u.dot(v)

np.int64(14)

#### Matrix-Vector Multiplication

In [8]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [9]:
v = np.array([1, 0.5, 2, 1])

In [10]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    k = U.shape[0]
    result = np.zeros(k)

    for i in range(k):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

#### Matrix-Matrix Multiplication

In [11]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [12]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [13]:
 def matrix_matrix_multiplication(U, V):
     assert U.shape[1] == V.shape[0]

     num_rows = U.shape[0]
     num_cols = V.shape[1]
     result = np.zeros((num_rows, num_cols))

     for i in range(num_cols):
         vi = V[:, i]

         Uvi = matrix_vector_multiplication(U, vi)
         result[:, i] = Uvi

Identity  Matrix

In [20]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
print("V: \n", V)
print("V * I: \n", (V.dot(I)))

V: 
 [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]
V * I: 
 [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]


Inverse

In [17]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [25]:
inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])