In [1]:
import numpy as np

#### Making Arrays with Numpy

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [13]:
a = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
print(a)
print(a[2])

[1 2 3 4 5 4 3 2 1]
3


In [15]:
a[2] = 10
print(a[2])

10


In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Multi-dimensional Arrays

In [19]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(n)
print(n[0, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [27]:
n[0, 1] = 20
print(n[0, 1])

20


In [28]:
n[2]

array([7, 8, 9])

In [31]:
n[2] = [9, 8, 7]
print(n[2])

[9 8 7]


In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 9,  8,  7]])

In [33]:
n[:, 1]

array([20,  5,  8])

In [36]:
n[:, 1] = [0, 1, 2]
n

array([[1, 0, 3],
       [4, 1, 6],
       [9, 2, 7]])

#### Randomly Generated Arrays

In [38]:
np.random.seed(2) #getting the same random numbers (pseudo-random)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.randn(5, 2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [41]:
np.random.randint(low=0, high=101, size=(5, 2))

array([[31, 66],
       [80, 52],
       [76, 50],
       [ 4, 90],
       [63, 79]])

#### Element-wise operations

In [50]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
a + 1

array([1, 2, 3, 4, 5])

In [52]:
a * 2

array([0, 2, 4, 6, 8])

In [55]:
b = (10 + (a * 2))**2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [56]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

#### Comparison Operations

In [57]:
a

array([0, 1, 2, 3, 4])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [60]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [59]:
a > b

array([False, False,  True,  True,  True])

In [61]:
a[a > b]

array([2, 3, 4])

 #### Summarizing Operations

In [63]:
a

array([0, 1, 2, 3, 4])

In [64]:
a.min()

np.int64(0)

In [65]:
a.max()

np.int64(4)

In [69]:
a.sum()

np.int64(10)

In [70]:
a.mean()

np.float64(2.0)

In [73]:
a.sum()

np.int64(10)

### numpy cheatsheet: https://media.datacamp.com/legacy/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf